name: alba
description: My personal portfolio website made with flutter web

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ^3.0.0

dependencies:
  carousel_slider: ^4.1.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.2
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/social/
    - assets/icons/techs/
    - assets/images/
    - assets/images/projects/
    - assets/info/
